---
# Github actions workflow file
name: Validate and update Resume Github Gist

on:
  push:
    branches:
      - master
      - feature/*
    paths-ignore:
      - "README.md"
jobs:
  validate-and-publish-resume:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Validate resume
        uses: Devleaps/jsonresume-generator@v1.1.0
        with:
          action: "validate"
      - name: Generate resume in PDF format
        uses: Devleaps/jsonresume-generator@v1.1.0
        with:
          action: "render"
          file: resume.json
          output-type: "pdf"
          theme-local: false
          theme-name: jsonresume-theme-stackoverflow
      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: resume
          path: resume.pdf
      - name: Update Resume Gist
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          gist_id: ${{ secrets.GIST_ID }}
          file_path: resume.json
