---
# Github actions workflow file
name: Validate and update Resume Github Gist

on:
    push:
        branches:
            - master
            - feature/*
        paths-ignore:
            - 'README.md'
jobs:
  validate-resume:
    name: Validate resume complies with schema
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Validate resume
        run: resume validate
  update-resume-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Update Resume Gist
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          gist_id: ${{ secrets.GIST_ID }}
          file_path: resume.json
